var labPrice = new Map();
labPrice.set("ECG", 10)
labPrice.set("X.Ray", 10)
labPrice.set("Ultra Sound", 10)
labPrice.set("Echocardiography", 10)
labPrice.set("Barium Studies", 10)
labPrice.set("IVP", 10)
labPrice.set("HSG", 10)
labPrice.set("Pathology", 10)
labPrice.set("FNAC /Biopsy", 10)
labPrice.set("Apperance", 10)
labPrice.set("PH", 10)
labPrice.set("SG", 10)
labPrice.set("Protein", 10)
labPrice.set("Sugar", 10)
labPrice.set("Ketone", 10)
labPrice.set("Nitrite", 10)
labPrice.set("Bilirubin", 10)
labPrice.set("Urobilinogen", 10)
labPrice.set("EPHT.CELL", 10)
labPrice.set("WBC", 10)
labPrice.set("RBC", 10)
labPrice.set("CAST", 10)
labPrice.set("Urine-HCG", 10)
labPrice.set("Occult Blood", 10)
labPrice.set("H.pylori AG", 10)
labPrice.set("VDRL/RPR", 10)
labPrice.set("HBsAG", 10)
labPrice.set("HCVAB", 10)
labPrice.set("RVI", 10)
labPrice.set("H.PYLOR(ab)", 10)
labPrice.set("ASO titer", 10)
labPrice.set("Serum-HCG", 10)
labPrice.set("SPECIMEN", 10)
labPrice.set("G.STAIN", 10)
labPrice.set("AFB", 10)
labPrice.set("WET FILM", 10)
labPrice.set("Cell-Count", 10)
labPrice.set("Diff", 10)
labPrice.set("Culture", 10)
labPrice.set("WAIDAL", 10)
labPrice.set("O", 10)
labPrice.set("H", 10)
labPrice.set("WEIL FELIX", 10)
labPrice.set("OX19", 10)
labPrice.set("BR.AB", 10)
labPrice.set("Consistency", 10)
labPrice.set("Direct", 10)
labPrice.set("Concentrated", 10)
labPrice.set("Ova/Parasite", 10)
labPrice.set("Puss Cell", 10)
labPrice.set("Bacteria", 10)
labPrice.set("BF", 10)
labPrice.set("CBC", 10)
labPrice.set("ERS", 10)
labPrice.set("BG&HR", 10)



module.exports = labPrice;